### ISSUE TITLE
ClientID conflict beetween clients in different MQTTLoader process's

### ISSUE THREAD

**Issue by namelew** [dist-sys/mqttloader#34]
Currenttly, the application don't allow combinations of clients in different process, like:

* In Process 1
```
broker="localhost"
port=1883
pub=10
sub=10
```
* In Process 2
```
broker="localhost"
port=1883
pub=10
sub=10
```

Where we try to run a test like this, is common to have a clientID conflict, with more then one process monitoring a client. Then, the throughput and latency are calculeted two times by client, with results in a number bigger then the real one. One way, to solve this is add a started id parameter in the config file, like Malaria does, or use a  random number to concat with the id.

Example with the starter id paramenter

* In Process 1
```
broker="localhost"

port=1883
pub=10
sub=10
starterID=0
```
* In Process 2
```
broker="localhost"
port=1883
starterID=10
pub=10
sub=10
```

One of this is possible?

**Comment by nabon** [comment]
I'm not sure if I understand your problem correctly, but we can run multiple MQTTLoader processes on a single machine.
Each process has HOST_ID, which is a random string generated in main/java/mqttloader/Constants.java
`HOST_ID = Util.genRandomChars(4);`

Client IDs include the HOST_ID like this:

- Subscribers: `ml-{HOST_ID}-s-{CLIENT_NUMBER}`
- Publishers: `ml-{HOST_ID}-p-{CLIENT_NUMBER}`

So, if you are facing a conflict of client IDs, you can lower the probability of having a conflict by enlarging the length of HOST_ID like the following:
`HOST_ID = Util.genRandomChars(12);`

Currently, MQTTLoader cannot calculate total throughput and latency over multiple processes.
Instead of that, you can calculate them by using the record file.
By setting the parameter "output", MQTTLoader writes the record of sending/receiving MQTT messages to a file.
The records in the file have timestamps.
So, you can calculate throughput and latency only with records within the time range that all processes were running.

**Comment by namelew** [comment]
Yes, I probably misundestand the ClientID generation. Thanks for clarifying, increase the length of the HOST_ID string must solve my problem.
